sudo: required 

services: 
  - docker 

before_install: 
  - docker build -t docker_image_react -f ./client/Dockerfile.dev ./client 

# To run the test script. Will return 0 if all tests passed, 0 if failed.  
script: 
  - docker run -e CI=true docker_image_react npm test

# Build images for each folder using their respective Dockerfiles 
after_success: 
  - docker build -t docker_image_multi_client -f ./client/Dockerfile ./client 
  - docker build -t docker_image_multi_nginx -f ./nginx/Dockerfile ./nginx 
  - docker build -t docker_image_multi_server -f ./server/Dockerfile ./server 
  - docker build -t docker_image_multi_worker -f ./worker/Dockerfile ./worker  